name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3

      - name: Install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: PNPM install
        run: pnpm install

      - name: Cache Rush Temp
        uses: actions/cache@v3
        with:
          path: |
            ./common/temp
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Rush Install
        run: pnpm exec rush update

      - name: Run unit tests
        run: pnpm run test

