name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 7.*

      - name: Install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: PNPM Install
        run: pnpm install --no-frozen-lockfile

      - name: Run unit tests
        run: pnpm run test

