name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3

      - name: Install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm exec rush install

      - name: Run unit tests
        run: pnpm run test
